### ISSUE TITLE
Create the Database

### ISSUE THREAD

**Issue by InstincDev** [InstincDev/secret-family-recipies#4]
-     Set up a MongoDB database to store recipe data.
-     Create a schema for the recipe model using Mongoose.
-     Implement CRUD operations for the recipe model.

**Comment by pooranjoyb** [comment]
I would like to work on this issue. Assign me this if you'd like to.
@InstincDev

**Comment by InstincDev** [comment]
> I would like to work on this issue. Assign me this if you'd like to. @InstincDev

Sure! Thank you for offering to help. I am creating this as part of the #10DayWebBuild challenge so the pace will be pretty quick. If you have any questions, feel free to ask.

**Comment by pooranjoyb** [comment]
Okk sure, I'll be up with the PR within a day or two. Thanks for assigning. @InstincDev

**Comment by InstincDev** [comment]
@pooranjoyb The Mongoose Schema needs to be based on TheMealDB API. www.themealdb.com/api/json/v1/1/search.php?f=a 
It should also include a createdBy section.

**Comment by pooranjoyb** [comment]
> @pooranjoyb The Mongoose Schema needs to be based on TheMealDB API. [www.themealdb.com/api/json/v1/1/search.php?f=a](http://www.themealdb.com/api/json/v1/1/search.php?f=a) It should also include a createdBy section.

Ok, I'm looking forward to implement this.
